version: '3.7'

services:
  sqldata:
    image: mcr.microsoft.com/azure-sql-edge:latest

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic

  customers.api:
    image: ${DOCKER_REGISTRY-}customers
    build:
      context: .
      dockerfile: Customers/Customers.Api/Dockerfile
    depends_on:
      - sqldata

  products.api:
    image: ${DOCKER_REGISTRY-}products
    build:
      context: .
      dockerfile: Products/Products.Api/Dockerfile
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:
    driver: local

networks:
  elastic:
    driver: bridge